nordicarz/urls.py
from django.contrib import admin
from django.urls import path, include
from trade.views import ListingList

urlpatterns = [
    path('', ListingList.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
    path('listings/', include('trade.urls')),
]

trade/urls.py
from . import views
from django.urls import path, include
from .views import AddListing, DeleteListing, EditListing

urlpatterns = [
    path('', views.ListingList.as_view(), name='home'),
    path('listings/', AddListing.as_view(), name='add_listing'),
  #  path('home/', views.ListingList.as_view(), name='home'),
    path('<slug:slug>/', views.ListingDetail.as_view(), name='listing_detail'),
    path('like/<slug:slug>/', views.ListingLike.as_view(), name='listing_like'),
    path('delete/<int:pk>/', DeleteListing.as_view(template_name='listing_confirm_delete.html'), name='delete_listing'),
    path('edit/<int:pk>/', EditListing.as_view(template_name='edit_listing.html'), name='edit_listing'),
]

trade/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))

#Defining the structure and attributes of the Listing model.
class Listing(models.Model): 
    
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200, unique=True)
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name="trade_listings")
    price = models.DecimalField(max_digits=10, decimal_places=2)
    currency = models.CharField(max_length=3, default='USD')
    engine = models.CharField(max_length=50)
    FUEL_CHOICES = [
        ('gasoline', 'Gasoline'),
        ('diesel', 'Diesel'),
        ('electric', 'Electric'),
        ('hybrid', 'Hybrid'),
    ]
    fuel = models.CharField(max_length=20, choices=FUEL_CHOICES)
    year = models.IntegerField()
    updated_on = models.DateTimeField(auto_now=True)
    description = models.TextField()
    featured_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(User, related_name='trade_likes', blank=True)

    # Deciding a descending order to each listing on the feed.
    class Meta():
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    # Calculates and returns number of likes on each listing.
    def number_of_likes(self):
        return self.likes.count()

# Defining the structure and attributes for the Comment model.
class Comment(models.Model):

    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    # Customizes and controls how the Comment model will be displayed.
class Meta():
    ordering = ['created_on']

    def __str__(self):
        return f"comment {self.body} by {self.name}"

trade/forms.py
from .models import Comment
from django import forms
from djrichtextfield.widgets import RichTextWidget
from .models import Listing

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields =('body',)

class ListingForm(forms.ModelForm):
    engine = forms.CharField(widget=RichTextWidget())
    fuel = forms.CharField(widget=RichTextWidget())

    class Meta:
        model = Listing
        fields = ['title', 'seller', 'price', 'currency', 'engine', 'fuel', 'year', 'description', 'featured_image', 'slug']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 5}),
        }
        labels = {
            'title': 'Listing Title',
            'description': 'Description',
            'seller': 'Seller',
            'price': 'Listing Price',
            'currency': 'Currency',
            'engine': 'Vehicle Engine',
            'fuel': 'Fuel',
            'year': 'Production Year',
            'featured_image': 'Vehicle Image',
            'slug': 'Slug',
        }

trade/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views import generic, View
from django.http import HttpResponseRedirect
from .models import Listing
from .forms import CommentForm
from django.views.generic import CreateView, DeleteView, UpdateView

from .forms import ListingForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.urls import reverse_lazy, reverse

class ListingList(generic.ListView):
    model = Listing
    queryset = Listing.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'
    paginate_by = 15

class ListingDetail(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = Listing.objects.filter(status=1)
        listing = get_object_or_404(queryset, slug=slug)
        comments = listing.comments.filter(approved=True).order_by('created_on')
        liked = False
        if listing.likes.filter(id=self.request.user.id).exists():
            liked = True

        price = listing.price
        currency = listing.price

        return render(
            request,
            "listing_detail.html",
            {
                "listing": listing,
                "description": listing.description,
                "comments": comments,
                "commented": False,
                "liked": liked,
                "comment_form": CommentForm(),
                "price": price,
                "currency": currency,
            },
        )

    def post(self, request, slug, *args, **kwargs):
        queryset = Listing.objects.filter(status=1)
        listing = get_object_or_404(queryset, slug=slug)
        comments = listing.comments.filter(approved=True).order_by('created_on')
        liked = False
        if listing.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.listing = listing
            comment.save()
        else:
            comment_form = CommentForm()

        return render(
            request,
            "listing_detail.html",
            {
                "listing": listing,
                "description": listing.description,
                "comments": comments,
                "commented": True,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )

class ListingLike(View):

    def post(self, request, slug):
        listing = get_object_or_404(Listing, slug=slug)

        if listing.likes.filter(id=request.user.id).exists():
            listing.likes.remove(request.user)
        else:
            listing.likes.add(request.user)

        return HttpResponseRedirect(reverse('listing_detail', args=[slug]))

class AddListing(LoginRequiredMixin, CreateView):
    template_name = 'trade/add_listing.html'
    model = Listing
    form_class = ListingForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.seller = self.request.user
        messages.success(self.request, 'Listing created. Waiting for approval.')
        return super(AddListing, self).form_valid(form)

class EditListing(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = "templates/edit_listing.html"
    model = Listing
    form_class = ListingForm
    success_url = reverse_lazy('home')

    def test_func(self):
        listing = self.get_object()
        return self.request.user == listing.seller

class DeleteListing(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Listing
    success_url = reverse_lazy('home')
    template_name = "templates/listing_confirm_delete.html"

    def test_func(self):
        listing = self.get_object()
        return self.request.user == listing.seller

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100">

<head>
    <title>Nordicarz Trade</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <script src="https://kit.fontawesome.com/42115b01ec.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->

    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}"><span class="brand">n<span class="red-o">ordic</span><span
                        class="thin">|carz</span></span></span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li  class="nav-item">
                        <a class="nav-link {% if url_name == 'add_listing' %}active{% endif %}" href="{% url 'add_listing' %}">New Listing</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
                <span class="navbar-text text-muted">
                    Nordicarz-Secure Vehicle Trades
                </span>
            </div>
        </div>
    </nav>
    
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }} 
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
                
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
        </div>
    </div>
    
    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <p class="m-0 text-center text-white">Made by Apollon Georgopoulos</p>
    </footer>
    <script>
        setTimeout(function() {
            let messages = document.getElementById("msg");
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 3000);
    </script>
</body>

</html>

templates/edit_listing.html
{% extends "base.html" %}

{% block title %}Edit Listing{% endblock %}

{% block content %} 
<div class="container">
    <form method="POST" enctype="multipart/form-data" class="p-2 form">
        <h1 class="text-center">Edit Listing</h1>
        {% csrf_token %}
        
        {{ form.as_p }}
        <div class="text-center">
            <button type="submit" class="btn btn-primary mt-2">Edit Listing</button>
        </div>
    </form>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    {% for listing in listing_list %}
        <div class="card mb-3">
            <div class="body">
                <div class="image-container">
                    {% if "placeholder" in listing.featured_image.url %}
                    <img class="card-img-top"
                        src="https://cdn.pixabay.com/photo/2014/04/27/00/43/traffic-332857_1280.jpg">
                    {% else %}
                    <img class="card-img-top" src="{{ listing.featured_image.url }}">
                    {% endif %}
                    <div class="image-flash">
                        <p class="seller">Seller: {{ listing.seller }}</p>
                    </div>
                </div>
                <a href="{% url 'listing_detail' listing.slug %}" class="listing-link">
                <h2 class="card-title">{{ listing.title }}</h2>
                <p class="card-text">{{ listing.excerpt }}</p>
                </a>
                <hr /> 
                <p class="card-text text-muted h6">{{ listing.created_on }} <i
                    <i class="fa-solid fa-heart"></i> {{ listing.number_of_likes }}</p>
            </div>
        </div>
    {% endfor %}
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}"
                class="page-link"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
            
{%endblock%}

templates/listing_confirm_delete.html
{% extends "base.html" %}

{% block title %} Delete listing {{ object.title }}{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="text-center mt-2">Confirm Listing Deletion</h1>
        <div class="d-flex justify-content-center pt-3">
            <form method="post" class="text-center">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{ object.title }}"?</p>
                <input type="submit" value="Confirm" class="btn btn-primary w-25">
            </form>
        </div>
    </div>
{% endblock %}

templates/listing_detail.html
{% extends 'base.html' %}
{% block content %}

{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <h1 class="post-title">{{ listing.title }}</h1>
                <p class="post-subtitle">{{ listing.seller }} | {{ listing.created_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                {% if "placeholder" in listing.featured_image.url %}
                <img src="https://cdn.pixabay.com/photo/2014/04/27/00/43/traffic-332857_1280.jpg" width="100%">
                {% else %}
                <img src="{{ listing.featured_image.url }}" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4 mt-3 left top">
            <div class="card-body">
                <p class="card-text">
                    {{ listing.description | striptags }}
                </p>
                <div class="row">
                    <div class="col-1">
                        <strong>
                            {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'listing_like' listing.slug %}" method="POST">
                                {% csrf_token %}
                                {% if liked %}
                                <button type="submit" name="tradelisting_id" value="{{ listing.slug }}" class="btn-like">
                                    <i class="fa-solid fa-heart"></i>
                                </button>
                                {% else %}
                                <button type="submit" name="tradelisting_id" value="{{ listing.slug }}" class="btn-like">
                                    <i class="fa-regular fa-heart"></i>
                                </button>
                                {% endif %}
                            </form>
                            {% else %}
                            <span class="text-secondary"><i class="fa-regular fa-heart"></i></span>
                            {% endif %}
                            <span class="text-secondary">{{ listing.number_of_likes }}</span>
                        </strong>
                    </div>
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6">
                                <h3>Price: {{ listing.price }} {{ listing.currency }}</h3>
                                <p>Engine: {{ listing.engine }}</p>
                                <p>Fuel: {{ listing.get_fuel_display }}</p>
                                <p>Year: {{ listing.year }}</p>
                            </div>
                        </div>
                    </div>

                    {% if request.user == listing.seller %}
                    <div class="text-center">
                        <a href="{% url 'edit_listing' listing.id %}" class="btn btn-primary w-25">Edit</a>
                        <a href="{% url 'delete_listing' listing.id %}" class="btn btn-primary w-25">Delete</a>
                    </div>
                    {% endif %}
                    <div class="col-1">
                        {% with comments.count as total_comments %}
                        <strong class="text-secondary"><i class="fa-regular fa-comments"></i> {{ total_comments }}</strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4 mt-3">
            <h3>Comments:</h3>
            <div class="card-body">
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        {{ comment.name }} 
                        <span class="text-muted font-weight-normal">{{ comment.created_on }}</span> wrote:
                    </p>
                    {{ comment.body | linebreaks }}
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4 mt-3">
            <div class="card-body">
                {% if commented %}
                <div class="alert alert-success" role="alert">
                    Comment awaiting approval
                </div>
                {% else %}

                {% if user.is_authenticated %}

                <h3>Leave a comment:</h3>
                <p>Posting as: {{ user.username}}</p>
                <form method="post" style="margin-top: 1.3em;">
                    {{ comment_form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-signup btn-lg">Submit</button>
                </form>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/post_detail.html
{% extends 'base.html' %} {% block content %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <h1 class="post-title">{{ listing title }}</h1>
                <p class="post-subtitle">{{ listing.seller }} | {{ listing.created_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                {% if "placeholder" in post.featured_image.url %}
                <img src="https://cdn.pixabay.com/photo/2014/04/27/00/43/traffic-332857_1280.jpg" width="100%">
                {% else %}
                <img src=" {{ listing.featured_image.url }}" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <p class="card-text ">
                    {{ post content | safe }}
                </p>
                <div class="row">

                    <div class="col-1">
                        <strong class="text-secondary"><i class="fa-solid fa-heart"></i> {{ listing.number_of_likes }} </strong>
                    </div>
                    <div class="col-1">
                        {% with comments.count as total_comments %}
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            {{ total_comments }}</strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Comments:</h3>
            <div class="card-body">
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        {{ comment.name }}
                        <span class=" text-muted font-weight-normal">
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    <!-- The body of the comment goes before the | -->
                    {{ comment.body | linebreaks }}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                <!-- For later -->
            </div>
        </div>
    </div>
</div>

{% endblock content %}

trade/templates/listings/listing.confirm.delete.html
{% extends "base.html" %}

{% block title %}Delete listing {{ object.title }}{% endblock %}
    <div class="container">
        <h1 class="text-center mt-2">Confirm Listing Deletion</h1>
        <div class="d-flex justify-content-center pt-3">
            <form method="post" class="text-center">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{object.title}}"?</p>
                <input type="submit" value="Confirm" class="btn btn-primary w-25">
            </form>
        </div>
    </div>
{% endblock %}

trade/templates/listings/listing_confirm_delete.html
{% extends "base.html" %}

{% block title %} Delete listing {{ object.title }}{% endblock %}
    <div class="container">
        <h1 class="text-center mt-2">Confirm Listing Deletion</h1>
        <div class="d-flex justify-content-center pt-3">
            <form method="post" class="text-center">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{ object.title }}"?</p>
                <input type="submit" value="Confirm" class="btn btn-primary w-25">
            </form>
        </div>
    </div>
{% endblock %}

trade/templates/trade/add_listing.html
{% extends "base.html" %}

{% block title %}AddListing{% endblock %}

{% block content %} 
<div class="container">
    <form method="POST" enctype="multipart/form-data" class="p-2 form">
        <h1 class="text-center">Add Listing</h1>
        {% csrf_token %}
        
        {{ form.as_p }}
        <div class="text-center">
            <button type="submit" class="btn btn-primary mt-2">Create Listing</button>
        </div>
    </form>
</div>
{% endblock %}